runtime: python310

service: upir

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  secure: always

- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always
