steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud config set app/cloud_build_timeout 1200
    gcloud app deploy app.yaml --project=$PROJECT_ID --quiet

timeout: '1200s'